### ISSUE TITLE
Issue with changing bone.rotation_mode to 'XYZ'

### ISSUE THREAD

**Issue by norajoby** [NumesSanguis/FACSvatar#31]
I tried implementing FACSvatar with Blender 2.82 with newer version of MB-LAB (1.7.8) and the following issue arises:

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "**path**/FACSvatar-master/blender/facsvatar_zeromq.py", line 243, in <module>
    bpy.ops.wm.facsvatar_zeromq()
  File "/Applications/Blender 2.82.app/Contents/Resources/2.82/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "**path**/FACSvatar-master/blender/facsvatar_zeromq.py", line 41, in __init__
    self.find_MBLabModel()
  File "**path**/FACSvatar-master/blender/facsvatar_zeromq.py", line 58, in find_MBLabModel
    bone.rotation_mode = 'XYZ'
AttributeError: Writing to ID classes in this context is not allowed: MBlab_sk1618120982.624969, Object datablock, error setting PoseBone.rotation_mode

location: /Applications/Blender 2.82.app/Contents/Resources/2.82/scripts/modules/bpy/ops.py:201

This issue doesn't arise with Blender 2.79 and MB-LAB 1.6.1a. 
I suspect the source of issue is this:
https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API/Animation_API

However I am not sure how to fix this. Any suggestions?

**Comment by aldelb** [comment]
Hi @norajoby ,
Have you find a solution ? I'm facing the same issue.

**Comment by NumesSanguis** [comment]
Hey, seems I completely overlooked this issue. At the moment I'm not actively working on this project anymore.

@aldelb Which branch are you using of FACSvatar? Can you confirm that this issue also appears on the v0.4.0 branch?:
https://github.com/NumesSanguis/FACSvatar/tree/v0.4.0

**Comment by aldelb** [comment]
Hello @NumesSanguis, thank for taking your time to answer. 
Yes, the issue appears on the V0.4.0 branch. I'm on windows 10 home and I followed the youtube tutorial and the doc online.

**Comment by NumesSanguis** [comment]
Hi @aldelb, some update in Blender/MB-Lab seems to have broken it then. I'm not sure when and if I have time to look into this, so you might have to dive into the Python code yourself. I'm glad to answer any questions you have though!
